name: 'NGINX configuration sync'
description: 'The action synchronizes NGINX configuration from a Git repository to a NGINX on Azure instance.'
inputs:
  client-id:
    description: 'The client ID '
    required: true
  tenant-id:
    description: 'The tenant ID'
    required: true
  subscription-id:
    description: 'The Azure subscription ID of the NGINX deployment'
    required: true
  resource-group-name:
    description: 'The resource group of the NGINX deployment'
    required: true
  nginx-deployment-name:
    description: 'The name of the NGINX deployment'
    required: true
  nginx-config-file-path:
    description: 'The file path of the NGINX configuration file in the Git repository'
    required: true
    default: './config/nginx.conf'
runs:
  using: "composite"
  steps:
    - name: 'Run Azure Login with OIDC'
      uses: azure/login@v1
      with:
        client-id: ${{ inputs.client-id }}
        tenant-id: ${{ inputs.tenant-id }}
        subscription-id: ${{ inputs.subscription-id }}
    - name: 'Deploy configuration to NGINX deployment'
      run: |
        ./deploy-config.sh ${{ inputs.subscription-id }} ${{ inputs.resource-group-name }} ${{ inputs.nginx-deployment-name }} ${{ inputs.nginx-config-file-path }}
      shell: bash
