name: 'NGINX configuration sync'
description: 'The action synchronizes NGINX configuration from a Git repository to an NGINX deployment on Azure.'
inputs:
  subscription-id:
    description: 'The Azure subscription ID of the NGINX deployment'
    required: true
  resource-group-name:
    description: 'The resource group of the NGINX deployment'
    required: true
  nginx-deployment-name:
    description: 'The name of the NGINX deployment'
    required: true
  nginx-config-relative-file-path:
    description: 'The relative file path of the NGINX configuration file in the Git repository'
    required: true
    default: './config/nginx.conf'
runs:
  using: "composite"
  steps:
    - name: 'Deploy configuration to the NGINX deployment in Azure'
      run: ${{github.action_path}}/src/deploy-config.sh ${{ inputs.subscription-id }} ${{ inputs.resource-group-name }} ${{ inputs.nginx-deployment-name }} ${{ inputs.nginx-config-relative-file-path }}
      shell: bash
